management:
  endpoints:
    web:
      exposure:
        include: 'health,env,loggers,info,metrics,threaddump,prometheus'
        exclude: shutdown
      expose: 'health,info,metrics,prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true